<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Attivo',
    'Assigned panels' => 'Pannelli assegnati',
    'Author' => 'Autore',
    'Avatar' => 'Avatar',
    'Banned' => 'Bandito',
    'Birthday' => 'Compleanno',
    'Category' => 'Categoria',
    'Comment' => 'Commento',
    'Created at' => 'Creato il',
    'Deleted' => 'Cancellato',
    'Description' => 'Descrizione',
    'Email' => '',
    'Firstname' => 'Nome',
    'Frequency' => 'Frequenza',
    'Gender' => 'Sesso',
    'Inactive' => 'Inattivo',
    'Ip Address' => 'Indirizzo IP',
    'Key' => 'Chiave',
    'Keywords' => 'Parola chiave',
    'Last action at' => 'Ultima attività il',
    'Lastname' => 'Cognome',
    'Link' => 'Collegamento',
    'Name' => 'Nome',
    'Name (admin view)' => 'Nome (vista amministratore)',
    'Name (user view)' => '@@Nome (vista utente)@@',
    'Other' => 'Altro',
    'Panel Manager' => 'Gestione Pannelli',
    'Parent' => 'Genitore',
    'Password' => '',
    'Port' => 'Porta',
    'Preview' => 'Anteprima',
    'Published at' => 'Pubblicato il',
    'Remember me' => 'Ricordami',
    'Site' => 'Sito',
    'Slug' => '',
    'Sort index' => 'Ordina indice',
    'Status' => 'Stato',
    'Tags' => 'Tags',
    'Text' => 'Testo',
    'Title' => 'Titolo',
    'Type' => 'Tipo',
    'Updated at' => 'Modificato il',
    'Updater' => 'Modificato da',
    'Username' => 'Nome utente',
    'Username or email' => 'Nome utente o email',
    'Value' => 'Valore',
    'Website' => 'Sito web',
];
