<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation for {name}' => 'Attivazione per {name}',
    'Articles' => 'Articoli',
    'Articles category &laquo;{title}&raquo;' => 'Categoria articoli &laquo;{title}&raquo;',
    'Articles tagged with &laquo;{name}&raquo;' => 'Articoli taggati con &laquo;{name}&raquo;',
    'Backend' => 'Amministrazione',
    'Birthday' => 'Compleanno',
    'Change password' => 'Cambia password',
    'Check your email for further instructions.' => 'Controlla la mail per ulteriori istruzioni.',
    'Confirm password' => 'Conferma password',
    'Contact' => 'Contatto',
    'Email' => '',
    'Error activate your account.' => 'Errore nell\'attivazione dell\'account.',
    'Female' => 'Femmina',
    'Firstname' => 'Nome',
    'Gender' => 'Maschio',
    'Hello {username}, follow the link below to confirm your email:' => 'Salve {username}, fai click sul link qui sotto per confermare la tua email:',
    'Hello {username}, follow the link below to reset your password:' => 'Привет {username}, fail click sul link qui sotto per reimpostare la tua password:',
    'Lastname' => 'Cognome',
    'Login' => 'Accedi',
    'Logout' => 'Esci',
    'Lost password' => 'Password dimenticata',
    'Male' => 'Maschio',
    'Name' => 'Nome',
    'New password saved.' => 'Nuova password salvata.',
    'Other' => 'Altro',
    'Page not found.' => 'Pagina non trovata.',
    'Password' => 'Password',
    'Password reset for {name}' => 'Reimpostazione password per {name}',
    'Password reset token cannot be blank.' => 'Il token per la reimpostazione della password non può essere vuoto.',
    'Request password reset' => 'Richiedi reimpostazione della password',
    'Reset password' => 'Reimposta password',
    'Save' => 'Salva',
    'Send' => 'Invia',
    'Send email' => 'Invia email',
    'Settings' => 'Impostazioni',
    'Show Panel' => 'Mostra Pannello',
    'Signup' => 'Iscrizione',
    'Sorry, we are unable to reset password for the provided email address.' => 'Purtroppo non siamo in grado di reimpostare la password per l\'indirizzo email fornito.',
    'Subject' => 'Oggetto',
    'Text' => 'Testo',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Grazie per averci contattati. Risponderemo il prima possibile.',
    'There was an error sending your message.' => 'C\'è stato un errore nell\'invio del messaggio.',
    'Update' => 'Modifica',
    'Username' => 'Nome utente',
    'Users' => 'Utenti',
    'Verification code' => 'Codice di verifica',
    'Website' => 'Sito web',
    'Wrong password reset token.' => 'Token di verifica errato.',
    'Your account has been successfully activated.' => 'L\'account è stato attivato con successo.',
    'Your account has been successfully created. Check your email for further instructions.' => 'L\'account è stato creato con successo. Controllare la mail per ulteriori istruzioni.',
    'Your message has been sent successfully.' => 'Il messaggio è stato spedito con successo.',
    'Your password has been successfully changed.' => 'La password è stata modificata con successo.',
];
