<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Assigned panels' => '',
    'Assigned users' => '',
    'Author' => 'Автор',
    'Avatar' => 'Аватар',
    'Banned' => '',
    'Birthday' => 'День рождения',
    'Category' => 'Категория',
    'Comment' => 'Комментарий',
    'Created at' => 'Время создания',
    'Deleted' => '',
    'Description' => 'Описание',
    'Email' => '',
    'Firstname' => 'Имя',
    'Frequency' => 'Частота',
    'Gender' => 'Пол',
    'Inactive' => '',
    'Ip Address' => '',
    'Key' => 'Ключ',
    'Keywords' => 'Ключевые слова',
    'Last action at' => 'Активность',
    'Lastname' => 'Фамилия',
    'Link' => 'Ссылка',
    'Name' => 'Имя',
    'Name (admin view)' => '',
    'Name (user view)' => '@@@@',
    'Open in new window' => '',
    'Other' => 'Прочее',
    'Panel Manager' => '',
    'Parent' => 'Родитель',
    'Password' => 'Пароль',
    'Port' => '',
    'Preview' => 'Анонс',
    'Published at' => 'Время публикации',
    'Remember me' => 'Запомнить меня',
    'Site' => '',
    'Slug' => 'ЧПУ',
    'Sort index' => 'Индекс сортировки',
    'Status' => 'Статус',
    'Tags' => 'Теги',
    'Text' => 'Текст',
    'Title' => 'Название',
    'Type' => '',
    'Updated at' => 'Время обновления',
    'Updater' => 'Обновивший',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или email',
    'VNC Password' => '',
    'Value' => 'Значение',
    'Website' => 'Веб-сайт',
];
